{{- if .Values.phpmyadmin.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "my-java-app.fullname" . }}-phpmyadmin-service
  labels:
    {{- include "my-java-app.labels" . | nindent 4 }}
    app.kubernetes.io/component: phpmyadmin
spec:
  type: {{ .Values.phpmyadmin.service.type }}
  selector:
    app.kubernetes.io/name: {{ include "my-java-app.name" . }}-phpmyadmin
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - protocol: TCP
      port: {{ .Values.phpmyadmin.service.port }}
      targetPort: 80
{{- end }}
