apiVersion: v1
kind: Secret
metadata:
  name: {{ include "my-java-app.secretName" . }}
  labels:
    {{- include "my-java-app.labels" . | nindent 4 }}
type: Opaque
stringData:
  mysql-root-password: {{ .Values.secrets.mysqlRootPassword | quote }}
  mysql-password: {{ .Values.secrets.mysqlPassword | quote }}
  mysql-replication-password: {{ .Values.secrets.mysqlReplicationPassword | quote }}
